---
#This is main playbook that fetch Splunk role and executes the play
#- hosts: "{{ Splunk_Server_Name }}"
- hosts: all
  connection: local
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - splunk
