#Example Variables
#splunk_server_name: 127.0.0.1
#splunk_image_inventory_path: /home/user/dpwnloads
#splunk_package_file_name: https://download.splunk.com/products/splunk/releases/7.0.2/linux/splunk-7.0.2-03bbabbd5c0f-linux-2.6-x86_64.rpm
#splunk_installation_temp_path: /opt/splunk/tmp
#splunk_version_name: splunk-7.0.2-03bbabbd5c0f-linux-2.6-x86_64.rpm


splunk_server_name: 
splunk_image_inventory_path: 
splunk_installation_temp_path:
splunk_version_name:
